language: python
services:
  - redis-server
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update
  - sudo apt-get install libasound2-dev libjack-jackd2-dev jackd2

after_success:
  - pip install coveralls
  - coverage run --source=app unittests.py
  - coveralls
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python unittests.py
