"""INIT

Revision ID: 56d5434a1b89
Revises: None
Create Date: 2013-11-07 23:18:05.053448

"""

# revision identifiers, used by Alembic.
revision = '56d5434a1b89'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
